#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : aioeventlet
Version  : 0.5.2
Release  : 38
URL      : http://pypi.debian.net/aioeventlet/aioeventlet-0.5.2.tar.gz
Source0  : http://pypi.debian.net/aioeventlet/aioeventlet-0.5.2.tar.gz
Summary  : asyncio event loop scheduling callbacks in eventlet.
Group    : Development/Tools
License  : Apache-2.0
Requires: aioeventlet-license = %{version}-%{release}
Requires: aioeventlet-python = %{version}-%{release}
Requires: aioeventlet-python3 = %{version}-%{release}
Requires: eventlet
Requires: trollius
BuildRequires : buildreq-distutils3
BuildRequires : eventlet
BuildRequires : greenlet
BuildRequires : python-mock
BuildRequires : trollius

%description
possible to write asyncio code in a project currently written for eventlet.
        
        aioeventlet allows to use greenthreads in asyncio coroutines, and to use

%package license
Summary: license components for the aioeventlet package.
Group: Default

%description license
license components for the aioeventlet package.


%package python
Summary: python components for the aioeventlet package.
Group: Default
Requires: aioeventlet-python3 = %{version}-%{release}

%description python
python components for the aioeventlet package.


%package python3
Summary: python3 components for the aioeventlet package.
Group: Default
Requires: python3-core
Provides: pypi(aioeventlet)
Requires: pypi(eventlet)

%description python3
python3 components for the aioeventlet package.


%prep
%setup -q -n aioeventlet-0.5.1
cd %{_builddir}/aioeventlet-0.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583524832
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python runtests.py --verbose || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/aioeventlet
cp %{_builddir}/aioeventlet-0.5.1/COPYING %{buildroot}/usr/share/package-licenses/aioeventlet/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aioeventlet/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
