#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : aioeventlet
Version  : 0.5.2
Release  : 29
URL      : https://files.pythonhosted.org/packages/ee/1a/1573ef35a49bfe0144a98a9bdd40ac5a692e9a117ac8735e682e03dc39ce/aioeventlet-0.5.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/ee/1a/1573ef35a49bfe0144a98a9bdd40ac5a692e9a117ac8735e682e03dc39ce/aioeventlet-0.5.2.tar.gz
Summary  : asyncio event loop scheduling callbacks in eventlet.
Group    : Development/Tools
License  : Apache-2.0
Requires: aioeventlet-python3
Requires: aioeventlet-license
Requires: aioeventlet-python
Requires: eventlet
Requires: trollius
BuildRequires : buildreq-distutils3
BuildRequires : eventlet
BuildRequires : greenlet
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : trollius

%description
possible to write asyncio code in a project currently written for eventlet.
        
        aioeventlet allows to use greenthreads in asyncio coroutines, and to use

%package license
Summary: license components for the aioeventlet package.
Group: Default

%description license
license components for the aioeventlet package.


%package python
Summary: python components for the aioeventlet package.
Group: Default
Requires: aioeventlet-python3

%description python
python components for the aioeventlet package.


%package python3
Summary: python3 components for the aioeventlet package.
Group: Default
Requires: python3-core

%description python3
python3 components for the aioeventlet package.


%prep
%setup -q -n aioeventlet-0.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532239360
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python runtests.py --verbose || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/aioeventlet
cp COPYING %{buildroot}/usr/share/doc/aioeventlet/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/aioeventlet/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
